name: SonarQube Scan

on:
  pull_request:
    branches:
      - main  # Adjust this to the branch you want to scan

jobs:
  sonar_scan:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' 

    - name: Install dependencies
      run: |
        npm install

    - name: Install SonarQube Scanner
      run: |
        curl -sSLo sonar-scanner.zip https://github.com/SonarSource/sonar-scanner-cli/releases/download/4.6.2.2472/sonar-scanner-4.6.2.2472-linux.zip
        unzip sonar-scanner.zip
        export PATH=$(pwd)/sonar-scanner-4.6.2.2472-linux/bin:$PATH

    - name: Run SonarQube Scan
      run: |
        sonar-scanner -Dsonar.projectKey=sonarqube-nodejs-project \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.login=sqp_a1467b114c4f45dba482674fb1926c6b919f2942

    - name: Upload SonarQube Results to GitHub
      uses: sonarsource/sonarcloud-github-action@v2
      with:
        sonar-token: sqp_a1467b114c4f45dba482674fb1926c6b919f2942
